### ISSUE TITLE
Connecting to Portal

### ISSUE THREAD

**Issue by Bjorntenbroeke** [Esri/AuGeo#10]
When connect to our in house running portal i get a error:

Error 400
Invalid client_id

I have admin credential
The portal url works fine in Survey123 and Collect
There is a point Feature in my Portal with the tags horizon and AuGeo

When I hit the login, I am redirected to my portal and also it logs in, so the username and credentials are ok. 

Am I missing something?

![68ab0337-e09a-4d7f-bda7-5574162427dc](https://user-images.githubusercontent.com/6517996/32041321-ef5f8554-ba33-11e7-81d2-7443214a26fb.jpeg)

**Comment by JohnHasthorpe** [comment]
@Bjorntenbroeke  

To get this working you just need to follow the steps in the following resource:
https://support.esri.com/en/technical-article/000012713

However in step A4, instead of using the following for the Add Item form:

> Title: survey123
> Type: Application
> Type Keywords: Application
> Tags: survey123

Use 

> Title: AuGeo
> Type: Application
> Type Keywords: Application
> Tags: AuGeo

and for step C3 instead of changing the App Id to **Survey123**, change it to **bdYfjMVTp89edmT9**

Don't do steps D, E and F.

**Comment by JohnHasthorpe** [comment]
Documentation:
[How To Add AuGeo as a registered application to your Portal.docx](https://github.com/Esri/AuGeo/files/1533842/How.To.Add.AuGeo.as.a.registered.application.to.your.Portal.docx)
