### ISSUE TITLE
Future of AuGeo app?

### ISSUE THREAD

**Issue by Elowan** [Esri/AuGeo#21]
hello there,

development news and things around AuGeo got quiet - is this app still in active development? Will the features suggested on this github be impelemented any time soon?

or was this just a kind of experimental project and it got canceled already?

Best regards,
Elowan

**Comment by dominikargast** [comment]
@Elowan Due to continued interest from developers, the AuGeo template has been updated to work with AppStudio 4.0 and the forthcoming AppStudio 4.1. 

Further work on AuGeo is currently not included in our development plan, but that may change in the future.

**Comment by ronaldsheaks** [comment]
I think this app opens serious possibilities for developers who want to work for themselves.

**Comment by Zengirl2** [comment]
I don't have hosting privileges to test the app using my own data--can you tell me if it is still possible to create point data for the app?

**Comment by JohnHasthorpe** [comment]
Hi @Zengirl2 - There is a requirement to create a feature service (with a point layer) within ArcGIS Online/Enterprise in order to use the app. Once created, the owner of the service (or a user that the service has been shared with) may sign into the app using their ArcGIS account in order to access it. There is no way to create local point data within the app.
